#!/usr/bin/env bash

# dmenu theming
lines="-l 20"
font="DejaVu Sans Mono"
fconf=':style=Boldu:size=10'
bg="-sb #0f0f0f"
selected="$(ps -a -u $USER | \
            dmenu -i  \
            $lines  $bg -fn '$font'$fconf | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | \
            dmenu -i -p "$selected will be killed, are you sure?" \
            $lines  $bg -fn '$font'$fconf )"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
